import Head from "next/head";
import React from "react";
import Home from "../containers/Home";

const App: React.FC = () => {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  );
};

export default App;
